<?php
 echo 'Hello,world!';
 $array = array(10,20,30);
 foreach ($array as $key => $value) {
 	echo $key . '=>' . $value . '<br>';
 }

// nekonekonekoneko.... 
// nekonekonekoneko.... 
// nekonekonekoneko.... 
// nekonekonekoneko.... 
// nekonekonekoneko.... 
// nekonekonekoneko.... 
// nekonekonekoneko.... 
// nekonekonekoneko.... 
// nekonekonekoneko.... 
// nekonekonekoneko.... 
// nekonekonekoneko.... 
// nekonekonekoneko.... 
// nekonekonekoneko.... 

 echo 'kuro';

echo 'from company computer (^^)';

?>
